### ISSUE TITLE
Console error after change gradient settings

### ISSUE THREAD

**Issue by javadsamiee** [artf/grapesjs-style-gradient#24]
<img width="1992" alt="image" src="https://user-images.githubusercontent.com/65819265/163820762-6ed25640-d6b4-4b0d-a32b-ff76a2e9151e.png">

**Comment by micker** [comment]
hello di you have some return @artf ?
we have same return

**Comment by artf** [comment]
New release should fix the issue https://github.com/artf/grapesjs-style-gradient/releases/tag/v3.0.1
