### ISSUE TITLE
BuildProps Background have problem with Gradient

### ISSUE THREAD

**Issue by javadsamiee** [artf/grapesjs-style-gradient#29]

**Comment by javadsamiee** [comment]
When I add gradient points the background show new layer for each gradient point with images layer

<img width="341" alt="image" src="https://user-images.githubusercontent.com/65819265/205000761-3fb8caa2-a9e2-4d49-957a-73e84ed95d6f.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/65819265/205000824-b440ef6d-dc59-4801-80b8-962e65711d09.png">

I'm using GrapesJS v0.20.1 and GrapesJS Style Gradient v3.0.1

**Comment by artf** [comment]
Hi @javadsamiee yes unfortunately the gradient itself conflicts with the built-in background property. If you need to keep the built-in background I'd suggest to use the latest https://github.com/artf/grapesjs-style-bg (now supported for newer GrapesJS versions)
