### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by grant007** [artf/grapesjs-style-gradient#3]
I visited the grapesjs-style-gradient demo and found that the gradient type is not appearing in decorations section of style manager. I cannot figure out what is wrong. Perhaps I do not understand how it is supposed to work. Please advise.

**Comment by alikabeer32** [comment]
I have the same problem

**Comment by artf** [comment]
Now the demo should work, here explained what happened https://github.com/artf/grapesjs/issues/2068
