### ISSUE TITLE
Upgrading the plugins packages to be compatible with the new Grapesjs Version

### ISSUE THREAD

**Issue by kanaihyakumar** [artf/grapesjs-style-gradient#32]
There are two packages which still outdated due to which there is an issue. It will be really great if anyone upgrade the below plugins to be compatible with the newer version:

1. [parser-postcss](https://github.com/GrapesJS/parser-postcss)
2. [style-gradient](https://github.com/GrapesJS/style-gradient)

Thank you in advance

**Comment by artf** [comment]
https://github.com/GrapesJS/style-gradient/pull/33
