### ISSUE TITLE
Plugin doesn't load 

### ISSUE THREAD

**Issue by MariusDK** [artf/grapesjs-style-gradient#4]
Hello @artf 

This is how i add the plugin.

```
plugins: ['gjs-style-gradient'],
pluginsOpts: {
        'gjs-style-gradient': {
          colorPicker: 'default',
          grapickOpts: {
            min: 1,
            max: 99,
          }
        }
      }
```

```
editor.StyleManager.addProperty('decorations', {
      name: 'Gradient',
      property: 'background-image',
      type: 'gradient',
      defaults: 'none'
});
```

And in package.json:

`"grapesjs-style-gradient": "1.0.5"`

**Comment by artf** [comment]
IDK @MariusDK 
The current demo is working properly with the latest release:
https://codepen.io/artf/pen/bYwdQG
This means that probably you're doing something wrong... otherwise provide a reproducible demo
